seed: 42
runtime:
  device: cuda

output:
  root_dir: outputs/visual_test/peel
  run_name: v2_small_local_attn_unet

data:
  root_dir: /mnt/workspace/zyj/data/processed/peel/peel_0722_1139
  # window
  window_size: 8
  stride: 1
  n_image_steps: 1
  action_horizon: 64
  # robot
  action_type: joint
  action_representation: relative
  # tatile
  use_tactile: false
  # camera
  camera_views: ['left_wrist_0', 'right_wrist_0']
  image_size: 224
  image_as_uint8: true
  use_camera_latent: true
  latent_cache_root_dir: /mnt/oss_data/zyj/latent_cache/peel_0722_1139/dinov2_s14
  # keys
  camera_key: camera
  tactile_key: tactile
  state_key: state_30hz
  action_key: action_30hz
  # norm
  norm:
    output_range: [-1, 1]
    max_windows: 100000
  # memory
  memory:
    enabled: false
    history_frames: 64
    sample_stride: 4
    recent_frame: 4   # n=t-n

models:
  fm:
    cond_dim: 256
    # vision — DINOv2 (timm)
    n_image_views: 2
    image_encoder_name: dinov2_small
    dino_model_name: vit_small_patch14_dinov2.lvd142m
    freeze_image_encoder: true
    image_pretrained: true
    image_feat_dim: 256
    view_pool: local_attn  # global_concat | local_pool | local_attn
    local_pool_size: 2
    local_attn_heads: 4
    local_attn_dropout: 0.1
    # tactile CNN
    use_tactile: false
    tactile_feat_dim: 256
    tactile_temporal_pool: conv1d   # mean | conv1d
    state_feat_dim: 256
    state_pool: flatten
    diffusion_step_embed_dim: 256
    velocity_model: unet  # unet | dit
    # unet config
    down_dims: [256, 512, 1024]
    kernel_size: 5
    n_groups: 8
    # dit config
    dit_hidden_dim: 512
    dit_depth: 14
    dit_num_heads: 8
    dit_mlp_ratio: 4.0
    dit_dropout: 0.1
    # common config
    num_inference_steps: 32
    solver: euler
  memory:
    method: fusion # fusion | multi-scale
    injection: concat_global_cond # cross_attn | concat_global_cond
    # multi-scale
    dim: 256
    num_queries: 3
    visual_heads: 4
    state_hidden_dim: 64
    state_layers: 2
    state_heads: 4
    dropout: 0.1
    cross_attn_layers: [3, 7, 11]
    # fusion
    visual_layers: 2
    state_channels: 128
    state_mem_dim: 64

train:
  batch_size: 1024
  num_workers: 32
  drop_last: true
  pin_memory: true
  persistent_workers: true
  prefetch_factor: 4
  epochs: 256
  grad_clip: 1.0
  use_amp: false
  open_loop_test_every: 300
  open_loop_test_max_batches: 16
  plot_samples: 64
  plot_dims: auto
  max_train_batches: null
  resume_path: null
  optimizer:
    lr: 3.0e-4
    min_lr: 1.0e-6
    weight_decay: 1.0e-4

checkpoint:
  save_every: 200

precompute:
  batch_size: 1024
  device: cuda
  overwrite: false
  output_path: null

deploy:
  action_process: abs_qpos # abs_qpos
  action_hz: 30.0
