# chahua_vq | eef | rel | view2 | tactile=false | camera_aug=false
seed: 42
runtime:
  device: cuda
output:
  root_dir: outputs/test3
  run_name: chahua_vq_eef_v2_rel
data:
  window_size: 8
  stride: 1
  n_image_steps: 1
  action_horizon: 32
  image_size: 224
  image_as_uint8: true
  camera_key: camera
  tactile_key: tactile
  state_key: state_30hz
  action_key: action_30hz
  norm:
    output_range:
    - -1
    - 1
    max_windows: 50000
  root_dir: /mnt/workspace/zyj/data/processed/chahua/chahua_0707_1839
  action_type: eef
  action_representation: relative
  use_tactile: false
  camera_views:
  - left_wrist_0
  - right_wrist_0
  use_camera_latent: true
  latent_cache_root_dir: ${data.root_dir}
  camera_augmentation: false
models:
  fm:
    cond_dim: 256
    image_encoder_name: dinov2_small
    dino_model_name: vit_small_patch14_dinov2.lvd142m
    freeze_image_encoder: true
    image_pretrained: true
    image_feat_dim: 256
    tactile_feat_dim: 256
    tactile_temporal_pool: conv1d
    state_feat_dim: 256
    state_pool: flatten
    action_horizon: 32
    n_action_steps: 32
    diffusion_step_embed_dim: 256
    down_dims:
    - 256
    - 512
    - 1024
    kernel_size: 5
    n_groups: 8
    num_inference_steps: 16
    solver: euler
    n_image_views: 2
    use_tactile: false
train:
  batch_size: 512
  num_workers: 16
  drop_last: true
  pin_memory: true
  persistent_workers: true
  prefetch_factor: 4
  epochs: 256
  grad_clip: 1.0
  use_amp: false
  open_loop_test_every: 300
  open_loop_test_max_batches: 16
  plot_samples: 64
  plot_dims: auto
  max_train_batches: null
  resume_path: null
  optimizer:
    lr: 0.0001
    min_lr: 1.0e-06
    weight_decay: 0.0001
checkpoint:
  save_every: 200
precompute:
  batch_size: 512
  device: cuda
  max_windows: null
  overwrite: true
  output_path: null
deploy:
  action_hz: 30.0
  action_process: abs_eef
